import os

PATH_TO_MEDIA_FOLDER = os.path.dirname(os.path.dirname(__file__))+'/media'
UPLOAD_RES_FOLDER = 'res'
UPLOAD_ASSET_FOLDER = 'asset'
UPLOAD_APK_FOLDER = 'apk'
UPLOAD_SHORT_DESC_FOLDER = 'short_description'
UPLOAD_FULL_DESC_FOLDER = 'full_description'
UPLOAD_APP_ICON_FOLDER = 'app_icon'
UPLOAD_LARGE_PROMO_FOLDER = 'large_promo'
UPLOAD_SCREENS_FOLDER = 'screens_folder'
UPLOAD_MARKET_FOLDER = 'market'
UPLOAD_SERTIFICATE_FOLDER = 'sertificate'
UPLOAD_SOURCE_FOLDER = 'source'
UPLOAD_APPDF_FOLDER = 'info_appdf'
UPLOAD_SCREENS_SCRIPT_FOLDER = 'script_screen'
UPLOAD_RES_SCRIPT_FOLDER = 'script_res'
UPLOAD_ASSET_SCRIPT_FOLDER = 'script_asset'
UPLOAD_ADS_SCRIPT_FOLDER = 'script_ads'