# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0005_auto_20150204_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='gen_script',
            field=models.FileField(upload_to=b'media/script_ads'),
        ),
        migrations.AlterField(
            model_name='description',
            name='path_app_icon',
            field=models.FileField(default=None, upload_to=b'media/app_icon'),
        ),
        migrations.AlterField(
            model_name='description',
            name='path_large_promo',
            field=models.FileField(default=None, upload_to=b'media/large_promo'),
        ),
        migrations.AlterField(
            model_name='description',
            name='path_screens_folder',
            field=models.FileField(default=None, upload_to=b'media/screens_folder'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='path_info_appdf',
            field=models.FileField(upload_to=b'media/appdf'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='path_script_screen',
            field=models.FileField(upload_to=b'media/script_screen'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='path_sertificate',
            field=models.FileField(upload_to=b'media/sertificate'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='path_source',
            field=models.FileField(upload_to=b'media/source'),
        ),
        migrations.AlterField(
            model_name='market',
            name='path_script',
            field=models.FileField(upload_to=b'media/market'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='path_to_apk',
            field=models.FileField(default=None, upload_to=b'media/apk'),
        ),
        migrations.AlterField(
            model_name='themedownloaditems',
            name='path',
            field=models.FileField(upload_to=b'media/theme_items'),
        ),
    ]
