# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0006_auto_20170801_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='gen_script',
            field=models.FileField(upload_to=b'script_ads'),
        ),
        migrations.AlterField(
            model_name='description',
            name='path_app_icon',
            field=models.FileField(default=None, upload_to=b'app_icon'),
        ),
        migrations.AlterField(
            model_name='description',
            name='path_large_promo',
            field=models.FileField(default=None, upload_to=b'large_promo'),
        ),
        migrations.AlterField(
            model_name='description',
            name='path_screens_folder',
            field=models.FileField(default=None, upload_to=b'screens_folder'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='path_info_appdf',
            field=models.FileField(upload_to=b'appdf'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='path_script_screen',
            field=models.FileField(upload_to=b'script_screen'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='path_sertificate',
            field=models.FileField(upload_to=b'sertificate'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='path_source',
            field=models.FileField(upload_to=b'source'),
        ),
        migrations.AlterField(
            model_name='market',
            name='path_script',
            field=models.FileField(upload_to=b'market'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='path_to_apk',
            field=models.FileField(default=None, upload_to=b'apk'),
        ),
        migrations.AlterField(
            model_name='themedownloaditems',
            name='path',
            field=models.FileField(upload_to=b'theme_items'),
        ),
    ]
